config/routes.rb
Rails.application.routes.draw do

  # page home
  root 'welcome#index'
  get '/home', to: 'welcome#index'

  # user routes for both purchasers and farmers
  #resources :products, only: [:index]


  resources :products

  resources :orders, only: [:index, :new, :show, :create]

  resources :users, shallow: true do
    resources :orders
    resources :products
  end
  # resources :farmers, only: [:update], controller: 'users', as: 'users'

  # login/logout authentication
  resources :sessions, only: [:new, :create, :destroy]
  get '/login', to: 'sessions#new'

  get '/cart', to: 'sessions#shopping_cart'
  # other resources

  post '/cart', to: 'sessions#add_to_cart'

end

app/models/farmer.rb
class Farmer < User
  has_many :products, foreign_key: "user_id"
  has_many :orders, through: :products

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :purchaser, foreign_key: "user_id"
  has_many :products
  has_many :farmers, through: :products

  after_create :generate_po_number

  def generate_po_number
    self.number = "P#{self.id.to_s.rjust(8, '0')}"
    self.save
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :order
  belongs_to :farmer, foreign_key: "user_id"

  def formatted_price
    "$#{"%.2f" % price}"
  end
end

app/models/purchaser.rb
class Purchaser < User
  has_many :orders, foreign_key: "user_id"
  has_many :products, through: :orders


end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  private
      #helper method gives access from inside a view
      helper_method :current_user, :cart, :cart_products, :is_in_cart?

      def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      end

      def authorize
        redirect_to login_path, alert: 'Not authorized - you must be logged in!' if current_user.nil?
      end

      def cart
        session[:cart] ||= []
      end

      def cart_products
        cart.map {|id| Product.find_by_id(id)}
      end

      def is_in_cart?(id)
        cart.include? id.to_s
      end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = current_user.orders
  end

  def show
    #@orders = current_user.orders
    @order = cart
  end

  def new
   # @order = Order.find_by_id(params[:id])
    @order = Order.new
    @products = current_user.products
  end

  def create
    @order = current_user.orders.build order_params
    if @order.save
    #  redirect_to , notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  def order_params
    params.require(:product).permit(:product)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :authorize, except: [:index]

  before_action :set_product, only: [:show, :edit, :update, :destroy]


  def index

   # binding.pry
  if current_user.type == "Farmer"
      @products = current_user.products
    else
      @products = Product.all
      @shopping_cart = session[:cart]
    end

  end

  def show
  end

  def new
   # @order = Order.find_by_id(params[:id])
    @product = Product.new
  end

  def edit
  end

  def create
    @product = current_user.products.build product_params
    #FIRST WAY  @product = Product.new(product_params)
    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end

  end

  def update
      if @product.update(product_params)
        redirect_to @product, notice: 'Product was successfully updated.'
       # render :show
      else
        render :edit
      end
  end

  def destroy
    @product.destroy
      redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    default_params = params.require(:product).permit(:category, :price, :taste_description, :quantity)
    name = params[:name][ params[:product][:category].downcase  ]
    default_params["name"] = name
    default_params
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id), notice: 'Logged in to account!'

    else
      flash.now.alert = 'Invalid login credentials - try again!'

      #starts over
      render 'new'
    end

  end

  def destroy
    session[:user_id] = nil
    session[:cart] = nil
    redirect_to root_path, notice: "Logged out!"
  end


  def add_to_cart
    cart.push(params[:product_id])
    redirect_to products_path
  end

  def shopping_cart
    render :cart
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index

  end

  def show
    @user = User.find_by_id(params[:id])
  end

  def new
   @user = User.new
  end

  def edit
    @user = User.find_by_id(params[:id])
    @user = @user.becomes User
    # binding.pr
  end


  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "You have successfully signed up!"

        redirect_to user_path(@user.id)
    else
      render :new
    end

  end

  def update
    @user = User.find_by_id(params[:id])
    if @user.update(user_params)
      redirect_to user_path, notice: 'Account was successfully updated.'
      # render :show
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :type,
      :business_name,
      :postal_code,
      :password,
      :password_confirmation)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FarmerStand</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class ="top">
<p>
  <% if current_user %>
    <% #Says welcome...user %>
    <strong>Welcome, <%= current_user.name %></strong>

    &nbsp;&nbsp;|&nbsp;&nbsp;
    <%= link_to 'Your Page', user_path(current_user) %>
    &nbsp;&nbsp;|&nbsp;&nbsp;
    <%= link_to 'Logout', session_path('dontmatter'), method: :delete %>
    &nbsp;&nbsp;|&nbsp;&nbsp;
    <%= link_to 'Cart', cart_path, class: 'glyphicon glyphicon-shopping-cart' %>
  <% else %>
    <%= link_to 'Login', login_path %>
    &nbsp;&nbsp;|&nbsp;&nbsp;
    <%= link_to 'Sign Up', new_user_path %>
  <% end %>

</p>

</div>

<%= yield %>

</body>
</html>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>The Orders...</h1>
<table class = "table table-striped table-hover">
  <thead>
    <tr>
      <th>Order Num</th>
      <th>Delivery Location</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @orders.each do |order| %>
      <tr>
        <td><%= order.number %></td>
        <td><%= order.delivery_location %></td>
        <td><%= link_to 'Show', order %></td>

    <% end %>
  </tbody>
</table>

<style>

body{
  text-align: center;
}

table {
  margin: 0 auto;
}
</style>

<br>


<%= link_to '<button type="button">Home</button>'.html_safe, user_path(current_user) %>

app/views/orders/show.html.erb
<h1>Your Orders</h1>
<div class ="orders">
<% if cart == nil %>
  <h2>You don't have any orders yet!</h2>

<% else %>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Category</th>
      <th>Name</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<tbody>
    <% cart.each do |product| %>
      <tr>
        <td><%= Product.find(product).order_id %></td>
        <td><%= Product.find(product).category %></td>
        <td><%= Product.find(product).name %></td>
        <td><%= Product.find(product).quantity %></td>
        <td><%= Product.find(product).formatted_price %></td>
        <td><%= Product.find(product).taste_description %></td>
        </tr>
    <% end %>
  </tbody>

  <% end %>

</div>

  <style>

body{
  text-align: center;
}

table {
  margin: 0 auto;
}
</style>


  <br>

  <%= link_to '<button class ="ordershome" type="button">Home</button>'.html_safe, user_path(current_user) %>

app/views/products/_form.html.erb
<link rel="stylesheet" href="assets/stylesheets/materialize.min.css">

<div class="form">

<%= form_for @product do |f| %>
<% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field type">
      <%= f.radio_button :category, 'Vegetable', :checked => true %>
      <%= label :category_type, 'Vegetable' %>
      <%= f.radio_button :category, 'Fruit' %>
      <%= label :category_type, 'Fruit' %>
      <%= f.radio_button :category, 'Dairy' %>
      <%= label :category_type, 'Dairy' %>
</div>
<br>
    <div class ="fruit hidden">
    <%= select_tag :"name[fruit]", options_for_select(['Watermelon', 'Oranges', 'Apples', 'Plums', 'Peaches', 'Nectarines', 'Grapes', 'Bananas', 'Cherries']) %>
    </div>

    <div class ="vegetable">
    <%= select_tag :"name[vegetable]", options_for_select(['Brocolli', 'Potatoes', 'Carrots', 'Onions', 'Lettuce', 'Turnips', 'Tomatoes', 'Asparagus', 'Cauliflower']) %>
    </div>

    <div class ="dairy hidden">
    <%= select_tag :"name[dairy]", options_for_select(['Eggs', 'Milk', 'Cheese', 'Yogurt']) %>
    </div>

<br>

 <div class="field">
    <strong><%= f.label :price, "Name your price" %>:</strong>
    <%= f.text_field :price %>
  </div>

<br>
<div class = "field">
  <strong><%= f.label :quantity, "Name your quantity" %>:</strong>
  <%= f.select :quantity, options_for_select(0..500), { prompt: "No Limit" } %>
</div>

  <br>
  <div class ="description">
    <strong><%= f.label :description, "Your description" %>:</strong>
    <%= f.text_area :taste_description %>
  </div>

<br>

<div class="actions"><%= f.submit %></div>

<%end%>

</div>

<style>

body{
  text-align: center;
}

.form{
  border: solid black;
  width: 40%;
  margin: 0 auto;
  padding: 15px;
}

.hidden {
  display: none;
}

</style>

<script>

  $(document).ready(function() {

    $('.type input').on('click', function(e) {
      console.log('clicked!', e.currentTarget.defaultValue);

      var type = e.currentTarget.defaultValue;

      if (type === "Fruit") {
        $('.fruit').removeClass('hidden');
        $('.vegetable').addClass('hidden');
        $('.dairy').addClass('hidden');

      }
      else if (type === "Vegetable") {
        $('.vegetable').removeClass('hidden');
        $('.fruit').addClass('hidden');
        $('.dairy').addClass('hidden');
      }
      else if (type === "Dairy"){
        $('.dairy').removeClass('hidden');
        $('.vegetable').addClass('hidden');
        $('.fruit').addClass('hidden');
      }

    });

  });

</script>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<br>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Products</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Category</th>
      <th>Name</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.category %></td>
        <td><%= product.name %></td>
        <td><%= product.quantity %></td>
        <td><%= product.formatted_price %></td>
        <td><%= product.taste_description %></td>

        <% if params["action"] == "new" || current_user.type == "Purchaser" %>

          <td><%= link_to(' Add to Cart', cart_path(:product_id => product.id), data: {confirm: 'Add to order?'}, method: "post", class: 'glyphicon glyphicon-shopping-cart') unless is_in_cart?(product.id) %></td>

        <% elsif params["action"] != "new" && current_user.type == "Farmer" %>

          <td><%= link_to 'Show', product %></td>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Remove', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>

    <% end %>
  </tbody>

</table>

<style>

body{
  text-align: center;
}

table {
  margin: 0 auto;
}
</style>

<br>

<% if params["action"] == "new" || current_user.type == "Purchaser" %>

<%= link_to '<button type="button">Add More</button>'.html_safe, new_user_product_path(current_user) %>
<%= link_to '<button type="button">Home</button>'.html_safe, user_path(current_user) %>
<%= link_to '<button type="button">Your Cart</button>'.html_safe, cart_path %>

<% elsif params["action"] != "new" && current_user.type == "Farmer" %>
<%= link_to '<button type="button">Add More</button>'.html_safe, new_user_product_path(current_user) %>
<%= link_to '<button type="button">Home</button>'.html_safe, user_path(current_user) %>

<% end %>

<br>

<div class="productsimage"></div>

app/views/products/new.html.erb
<h1>Add da produce</h1>
<p>

<%= render 'form' %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class = "product_view">
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Taste Description:</strong>
  <%= @product.taste_description %>
</p>
</div>


<style>

body {
  text-align: center;
}

.product_view{
  border: solid black;
  margin: 0 auto;
  width: 50%;
}

</style>

<br>

<%= link_to '<button type="button">View All Products</button>'.html_safe, products_path %>
<%= link_to '<button type="button">Add More</button>'.html_safe, new_product_path %>

app/views/users/_form.html.erb
<div class="signup">
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>

    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field form-group">
    <%= f.label :your_name %>:
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <br>

  <div class="field form-group">
    <%= f.label :your_email %>:
    <%= f.text_field :email, class: 'form-control' %>
  </div>

  <br>

  <% if params["action"] == "new" %>
    <div class="field type">
        <%= f.radio_button :type,  'Purchaser', checked: true %>
        <%= label :type_purchaser, 'Purchaser' %>
        <%= f.radio_button :type,  'Farmer' %>
        <%= label :type_farmer,    'Farmer' %>
    </div>
    <br>
  <% end %>

  <% if params["action"] == "new" || @user.type == "Farmer" %>
  <div class="field farmer-only form-group">
    <%= f.label :business_name %>:
    <%= f.text_field :business_name, class: 'form-control' %>
    <br><br>
  </div>

  <div class ="field farmer-only form-group">
    <%= f.label :postal_code %>:
    <%= f.text_field :postal_code, class: 'form-control' %>
    <br><br>
  </div>

  <% end %>

  <div class="field form-group">
    <%= f.label :your_password %>:
    <%= f.password_field :password, class: 'form-control'%>
  </div>
  <br>
  <div class="field form-group">
    <%= f.label :password_confirmation %>:
    <%= f.password_field :password_confirmation, class:'form-control' %>
  </div>
  <br>

  <div class="actions button"><%= f.submit %></div>
<% end %>

</div>



<script>

  $(document).ready(function() {

    $('.type input').on('click', function(e) {
      console.log('clicked!', e.currentTarget.defaultValue);

      var type = e.currentTarget.defaultValue;

      if (type === "Farmer") {
        $('.farmer-only').removeClass('hidden');
      } else {
        $('.farmer-only').addClass('hidden');
      }
    });

    $("input[checked]").trigger('click');
  });

</script>

app/views/users/edit.html.erb
<h1>Update your information</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<title>Da Farmer Stand</title>
<h1>Da Farmer Stand</h1>
<p id="notice"><%= notice %></p>

<h2>To buy or sell goods sign up and become a member!</h2>


  <% if @user.type == "Purchaser" %>
    <table class ="consumer-only hidden">
    <tr>
      <td>
      <%= link_to '<button class="consumer" type="button">Update Your Account</button>'.html_safe, edit_user_path(@current_user) %>
      </td>
      <td>
    <%= link_to '<button class="consumer" type="button">Check ORDERS</button>'.html_safe, orders_path %>
      </td>
    </tr>
    <tr>
      <td>
      <%= link_to '<button class="consumer" type="button">MAKE AN ORDER Here</button>'.html_safe, products_path %>

      </td>
      <td id="account">
      </td>
    </tr>
    </table>

  <% elsif @user.type == "Farmer" %>
    <table class ="consumer-only hidden">
    <h1> FARMER </h1>
    <tr>
      <td>
    <%= link_to '<button class="consumer" type="button">Add Your Products</button>'.html_safe, new_product_path%>
      </td>
      <td>
    <%= link_to '<button class="consumer" type="button">Check Your Inventory</button>'.html_safe, products_path %>
      </td>
    </tr>
    <tr>
      <td>
    <%= link_to '<button class="consumer" type="button">EDIT YOUR ACCOUNT</button>'.html_safe, edit_user_path(@current_user)%>
      </td>
      <td id="account">
      </td>
    </tr>
    </table>

    <% end %>

<style>

body{
  text-align: center;
}
table {
  margin: 0 auto;
}

.container {
  margin: 0 auto;
}

.consumer{
  height: 150px;
  width: 150px;
}

</style>

app/views/users/new.html.erb
<h1>Sign up as a member!</h1>
<h2>Buy fresh, local food, and get it delivered.</h2>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>Da Farmer Stand</h1>
<p id="notice"><%= notice %>

<br>
<h2>Your home page</h2>

<br>
  <% if @user.type == "Purchaser" %>
      <%= link_to '<button class="btn btn-primary btn-lg btn-block" type="button">Update Your Account</button>'.html_safe, edit_user_path(@user) %>
      <br>
      <%= link_to '<button class="btn btn-primary btn-lg btn-block" type="button">Check your Order</button>'.html_safe, order_path(current_user) %>
      <br>
      <%= link_to '<button class="btn btn-primary btn-lg btn-block" type="button">Make an Order</button>'.html_safe, products_path %>

  <% elsif @user.type == "Farmer" %>
    <br>
    <%= link_to '<button class="btn btn-primary btn-lg btn-block" type="button">Add Your Products</button>'.html_safe, new_user_product_path(current_user) %>
    <br>
    <%= link_to '<button class="btn btn-primary btn-lg btn-block" type="button">Check Your Inventory</button>'.html_safe, user_products_path(current_user) %>
    <br>
    <%= link_to '<button class="btn btn-primary btn-lg btn-block" type="button">Update Account</button>'.html_safe, edit_user_path(@user)%>
  <% end %>


<div class="userpage">

</div>


<style>

body{
  text-align: center;
}

</style>

app/views/welcome/index.html.erb
<title>Da Farmer Stand</title>

<h1>Da Farmer Stand</h1>
<br>

<br>

<span class="intro">To buy or sell goods sign up and become a member!</span>

<div class="welcome">
</div>